apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - zerofs.yaml

# Override the driver image without editing manifests:
# kustomize edit set image halceon/zerofs-csi-driver=halceon/zerofs-csi-driver:<tag>
images:
  - name: halceon/zerofs-csi-driver
    newName: halceon/zerofs-csi-driver
